### ISSUE TITLE
When page tabs have an all white background, tabs should still have some sort of separator.

### ISSUE THREAD

**Issue by CameronBanga** [PalmerAL/min#22] opened 2016-04-13 17:20 UTC
When I believe I'm viewing a page that has white text, the tab bar background matches to become all white. When this happens, there's no sort of separator between tabs, which is a bit messy and makes the entire bar a bit difficult to understand.

![screen shot 2016-04-13 at 12 17 55 pm](https://cloud.githubusercontent.com/assets/611354/14502653/f46f1900-0171-11e6-9d6a-4a3952c1c8f3.png)

The bar works as expected (albeit the separation colors are a bit light) when viewing a page with black text. This is a much better experience in differentiating the proper click area for switching between tabs.

<img width="645" alt="screen shot 2016-04-13 at 12 18 28 pm" src="https://cloud.githubusercontent.com/assets/611354/14502668/098903b4-0172-11e6-8b6f-017114da6764.png">

**Comment by Porco-Rosso** [comment] 2016-04-13 21:30
+1

**Comment by PalmerAL** [comment] 2016-04-13 22:40
Duplicate of #20.

**Closed by PalmerAL** 2016-04-13 22:40 UTC
