### ISSUE TITLE
Swiping on Tab Titles reversed if you don't have "natural" scroll direction.

### ISSUE THREAD

**Issue by itsgreggreg** [PalmerAL/min#87] opened 2016-04-21 04:18 UTC
1) Be on mac
2) In Trackpad preferences un-check "Scroll Direction: Natural"
3) Use swipe gestures on the tab bar
4) See that they are reversed

**Comment by PalmerAL** [comment] 2016-04-21 16:57
Duplicate of #27.

**Closed by PalmerAL** 2016-04-21 16:57 UTC
