### ISSUE TITLE
Little CSS bug

### ISSUE THREAD

**Issue by MichaelHemingway** [PalmerAL/min#45] opened 2016-04-16 01:50 UTC
![screen shot 2016-04-15 at 9 47 54 pm](https://cloud.githubusercontent.com/assets/13852458/14578337/d825cb2a-0353-11e6-9069-b07d3c71fe00.png)

Not a very nice start (page). 
This is on a 21-inch mid-2011 iMac running OSX 10.11.4.

**Comment by PalmerAL** [comment] 2016-04-16 01:57
Duplicate of #12.

 I should have time to fix this tomorrow.

**Closed by PalmerAL** 2016-04-16 01:57 UTC
