### ISSUE TITLE
Builds and runs on Linux, but doesn't work

### ISSUE THREAD

**Issue by cassidyjames** [PalmerAL/min#23] opened 2016-04-13 17:41 UTC
The window opens, but nothing works.

**Comment by cassidyjames** [comment] 2016-04-13 17:42
Fwiw, I'm running on elementary OS .04 Loki (based on Ubuntu 16.04 Xenial Xerus)

**Comment by idle-zealot** [comment] 2016-04-13 19:12
Experiencing what I believe to be the same issue. The page seems to be caught in a loop, reloading again and again. Running 64 bit Arch.

The binary version works fine on my system.

**Comment by PaulBGD** [comment] 2016-04-13 22:50
Fixed with #30

**Comment by idle-zealot** [comment] 2016-04-15 23:51
Can confirmed fixed.

**Comment by PalmerAL** [comment] 2016-04-16 00:10
Ok, I'll close this then.

**Closed by PalmerAL** 2016-04-16 00:10 UTC
